// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahGVrajjHxagS0f-pz5tfVPZgmpSlP5Y',
    appId: '1:898533166414:web:94cc1b62497e2a3a1aa21f',
    messagingSenderId: '898533166414',
    projectId: 'random-habit-app',
    authDomain: 'random-habit-app.firebaseapp.com',
    storageBucket: 'random-habit-app.firebasestorage.app',
    measurementId: 'G-QZ5C53B9HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmG3F0qy8ToEXSE4kXbaJ_5Xo7QJzB5g',
    appId: '1:898533166414:android:659ab783ba911d341aa21f',
    messagingSenderId: '898533166414',
    projectId: 'random-habit-app',
    storageBucket: 'random-habit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzam7QxVl8vH5yngsy4-tkxo5RTPahuzs',
    appId: '1:898533166414:ios:e905496c5872a0701aa21f',
    messagingSenderId: '898533166414',
    projectId: 'random-habit-app',
    storageBucket: 'random-habit-app.firebasestorage.app',
    iosBundleId: 'com.example.randomhabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzam7QxVl8vH5yngsy4-tkxo5RTPahuzs',
    appId: '1:898533166414:ios:c2746b75c87b70f01aa21f',
    messagingSenderId: '898533166414',
    projectId: 'random-habit-app',
    storageBucket: 'random-habit-app.firebasestorage.app',
    iosBundleId: 'com.example.rogerWebb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAahGVrajjHxagS0f-pz5tfVPZgmpSlP5Y',
    appId: '1:898533166414:web:77c58e8599fd15521aa21f',
    messagingSenderId: '898533166414',
    projectId: 'random-habit-app',
    authDomain: 'random-habit-app.firebaseapp.com',
    storageBucket: 'random-habit-app.firebasestorage.app',
    measurementId: 'G-6JLLYMBYPQ',
  );

}